import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
import { fonts } from '../../theme/Fonts';
import { Colors } from '../../theme/Colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    scrollContent: {
        paddingBottom: hp('4%'),
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: wp('100%'),
        marginTop: hp('1.8%'),
        paddingHorizontal: wp('6%'),
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
    },
    headerTitle: {
        fontSize: wp('5%'),
        fontFamily: fonts.SemiBold,
        textAlign: 'center',
        flex: 1,
        marginRight: wp('11%'),
    },
    titleSection: {
        marginTop: hp('3%'),
        paddingHorizontal: wp('6%'),
    },
    mainTitle: {
        fontSize: wp('5%'),
        fontFamily: fonts.Bold,
        color: '#1F2937',
        marginBottom: hp('0.5%'),
    },
    subtitle: {
        fontSize: wp('3.5%'),
        fontFamily: fonts.Regular,
        color: '#6B7280',
    },
    card: {
        width: wp('92%'),
        minHeight: hp('45%'),
        alignSelf: 'center',
        marginTop: hp('3.5%'),
        borderRadius: wp('6%'),
        overflow: 'hidden',
        position: 'relative',
    },
    summaryCard: {
        width: wp('92%'),
        minHeight: hp('40%'),
        alignSelf: 'center',
        marginTop: hp('2.5%'),
        borderRadius: wp('6%'),
        overflow: 'hidden',
        position: 'relative',
    },
    bodyCard: {
        width: wp('92%'),
        minHeight: hp('35%'),
        alignSelf: 'center',
        marginTop: hp('2.5%'),
        borderRadius: wp('5.3%'),
        borderWidth: 1,
        borderColor: '#F3F4F6',
        overflow: 'hidden',
        position: 'relative',
    },
    cardContent: {
        padding: wp('6%'),
        zIndex: 1,
    },
    cardTitle: {
        fontSize: wp('4.5%'),
        fontFamily: fonts.Bold,
        color: '#111827',
        marginBottom: hp('2.5%'),
    },
    summaryList: {
        width: '100%',
        marginBottom: hp('2%'),
    },
    summaryItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: hp('1.5%'),
        width: '100%',
    },
    summaryLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    summaryIconContainer: {
        width: wp('12%'),
        alignItems: 'center',
        justifyContent: 'center',
    },
    summaryLabel: {
        fontSize: wp('4.2%'),
        fontFamily: fonts.Regular,
        color: '#7C8394',
        marginLeft: wp('2%'),
        flexShrink: 1,
    },
    summaryValue: {
        fontSize: wp('4.5%'),
        fontFamily: fonts.Bold,
        color: '#111827',
        textAlign: 'right',
        minWidth: wp('15%'),
    },
    bmiSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: hp('1%'),
        marginBottom: hp('1%'),
    },
    bmiValueContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        width: '30%',
    },
    bmiValue: {
        fontSize: wp('11%'),
        fontFamily: fonts.Bold,
        color: '#111827',
        lineHeight: wp('12%'),
    },
    bmiLabel: {
        fontSize: wp('4%'),
        fontFamily: fonts.Medium,
        color: '#7C8394',
        marginTop: hp('0.5%'),
    },
    bmiMessageContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        width: '65%',
    },
    crushingItText: {
        fontSize: wp('4%'),
        fontFamily: fonts.Bold,
        color: '#1F2937',
        marginTop: hp('1.2%'),
    },
    crushingItSubText: {
        fontSize: wp('3%'),
        fontFamily: fonts.Regular,
        color: '#6B7280',
        textAlign: 'center',
        marginTop: hp('0.5%'),
    },
    needsSectionTitle: {
        fontSize: wp('4.5%'),
        fontFamily: fonts.Bold,
        color: '#111827',
        marginTop: hp('4%'),
        marginBottom: hp('2.5%'),
    },
    needsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: wp('2.5%'),
    },
    needItem: {
        alignItems: 'center',
        flex: 1,
    },
    needValue: {
        fontSize: wp('4.5%'),
        fontFamily: fonts.Bold,
        color: '#111827',
        marginBottom: hp('0.5%'),
    },
    needLabel: {
        fontSize: wp('3.8%'),
        fontFamily: fonts.Regular,
        color: '#7C8394',
    },
    mealPlanSection: {
        marginTop: hp('4%'),
        paddingHorizontal: wp('6%'),
    },
    sectionTitle: {
        fontSize: wp('4.5%'),
        fontFamily: fonts.Bold,
        color: '#1F2937',
        marginBottom: hp('0.5%'),
    },
    sectionSubtitle: {
        fontSize: wp('3.5%'),
        fontFamily: fonts.Regular,
        color: '#6B7280',
        marginBottom: hp('2.5%'),
    },
    largeMealCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: wp('6%'),
        marginBottom: hp('2.5%'),
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#F3F4F6',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 3,
    },
    largeMealImage: {
        width: '100%',
        height: hp('22%'),
    },
    largeMealDetails: {
        padding: wp('5%'),
    },
    mealTitle: {
        fontSize: wp('4.5%'),
        fontFamily: fonts.Bold,
        color: '#111827',
    },
    mealDesc: {
        fontSize: wp('3.5%'),
        fontFamily: fonts.Regular,
        color: '#6B7280',
        marginTop: hp('0.5%'),
    },
    badgesContainer: {
        flexDirection: 'row',
        marginTop: hp('2%'),
        gap: wp('2%'),
    },
    badge: {
        backgroundColor: '#F3F4F6',
        paddingHorizontal: wp('3%'),
        paddingVertical: hp('0.7%'),
        borderRadius: wp('2%'),
    },
    badgeText: {
        fontSize: wp('3%'),
        fontFamily: fonts.Medium,
        color: '#374151',
    },
    cardBottom: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginTop: hp('2.5%'),
    },
    priceContainer: {
        flex: 1,
    },
    originalPrice: {
        fontSize: wp('3.5%'),
        color: '#9CA3AF',
        textDecorationLine: 'line-through',
    },
    currentPriceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: hp('0.2%'),
    },
    currentPrice: {
        fontSize: wp('5%'),
        fontFamily: fonts.Bold,
        color: '#111827',
    },
    discountLabel: {
        fontSize: wp('3.5%'),
        fontFamily: fonts.Bold,
        color: '#EF4444',
        marginLeft: wp('2%'),
    },
    includesText: {
        fontSize: wp('3%'),
        color: '#9CA3AF',
        marginTop: hp('0.5%'),
    },
    buyBtn: {
        backgroundColor: '#FF6B35',
        paddingHorizontal: wp('6%'),
        paddingVertical: hp('1.5%'),
        borderRadius: wp('5%'),
    },
    viewAllButton: {
        alignSelf: 'flex-end',
        paddingVertical: hp('1.5%'),
        marginTop: hp('1.2%'),
    },
    viewAllText: {
        fontSize: wp('4%'),
        fontFamily: fonts.Bold,
        color: '#FF6B35',
        textDecorationLine: 'underline',
    },
    mealImageContainer: {
        width: '100%',
        height: hp('22%'),
        backgroundColor: '#F3F4F6',
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
});
